import { TFile, TFolder } from 'obsidian';

export class MetadataManager {
    constructor(plugin) {
        this.plugin = plugin;
        this.app = plugin.app;
        this.cacheFolderName = '.colophon-cache';
    }

    setup() {
        // 1. Initial Indexing of all .colophon files
        this.app.workspace.onLayoutReady(async () => {
            await this.ensureCacheFolder();
            await this.indexAllFiles();
        });

        // 2. React to file changes
        this.plugin.registerEvent(
            this.app.vault.on('modify', async (file) => {
                if (file instanceof TFile && file.extension === 'colophon') {
                    await this.indexFile(file);
                }
            })
        );

        // 3. React to renames (to keep internal links valid and sync shadow files)
        this.plugin.registerEvent(
            this.app.vault.on('rename', async (file, oldPath) => {
                if (file instanceof TFile) {
                    if (file.extension === 'colophon') {
                        await this.handleColophonRename(file, oldPath);
                    } else {
                        await this.handleGenericRename(file, oldPath);
                    }
                }
            })
        );

        // 4. React to deletions
        this.plugin.registerEvent(
            this.app.vault.on('delete', async (file) => {
                if (file instanceof TFile && file.extension === 'colophon') {
                    await this.removeShadowFile(file);
                }
            })
        );
    }

    async ensureCacheFolder() {
        if (!(await this.app.vault.adapter.exists(this.cacheFolderName))) {
            await this.app.vault.createFolder(this.cacheFolderName);
        }
    }

    async indexAllFiles() {
        const files = this.app.vault.getFiles().filter(f => f.extension === 'colophon');
        for (const file of files) {
            await this.indexFile(file);
        }
    }

    async indexFile(file) {
        try {
            const content = await this.app.vault.read(file);
            const data = JSON.parse(content);
            
            const links = [];
            const blockIds = [];

            // Recursive extraction
            this.extractMetadata(data.doc, links, blockIds);

            // Create/Update shadow markdown file for indexing
            await this.updateShadowFile(file, links, blockIds);
        } catch (err) {
            console.error(`Colophon: Failed to index ${file.path}`, err);
        }
    }

    extractMetadata(node, links, blockIds) {
        if (!node) return;

        // Extract Block IDs
        if (node.attrs && node.attrs.id) {
            blockIds.push(node.attrs.id);
        }

        // Extract Links
        if (node.type === 'internalLink' && node.attrs && node.attrs.target) {
            links.push(node.attrs.target);
        }

        // Recurse content
        if (node.content && Array.isArray(node.content)) {
            node.content.forEach(child => this.extractMetadata(child, links, blockIds));
        }
    }

    async updateShadowFile(file, links, blockIds) {
        const shadowPath = `${this.cacheFolderName}/${file.path.replace(/\//g, '_')}.md`;
        
        let mdContent = `---
colophon_origin: "${file.path}"
---
# Shadow File for Indexing Colophon

This file is automatically generated by the Colophon plugin to enable backlinks and graph support. 
DO NOT EDIT MANUALLY.

## Links
${links.map(l => `- [[${l}]]`).join('\n')}

## Blocks
${blockIds.map(id => `- Block ^${id}`).join('\n')}
`;

        if (await this.app.vault.adapter.exists(shadowPath)) {
            const currentShadow = await this.app.vault.adapter.read(shadowPath);
            if (currentShadow !== mdContent) {
                await this.app.vault.adapter.write(shadowPath, mdContent);
            }
        } else {
            await this.app.vault.create(shadowPath, mdContent);
        }
    }

    async removeShadowFile(file) {
        const shadowPath = `${this.cacheFolderName}/${file.path.replace(/\//g, '_')}.md`;
        if (await this.app.vault.adapter.exists(shadowPath)) {
            const shadowFile = this.app.vault.getAbstractFileByPath(shadowPath);
            if (shadowFile) await this.app.vault.delete(shadowFile);
        }
    }

    async handleColophonRename(file, oldPath) {
        // Delete old shadow file
        const oldShadowPath = `${this.cacheFolderName}/${oldPath.replace(/\//g, '_')}.md`;
        if (await this.app.vault.adapter.exists(oldShadowPath)) {
            const oldShadowFile = this.app.vault.getAbstractFileByPath(oldShadowPath);
            if (oldShadowFile) await this.app.vault.delete(oldShadowFile);
        }
        // Create new one
        await this.indexFile(file);
    }

    async handleGenericRename(file, oldPath) {
        // If a non-colophon file is renamed, we need to update any .colophon files that link to it.
        const allFiles = this.app.vault.getFiles().filter(f => f.extension === 'colophon');
        
        for (const colophonFile of allFiles) {
            let content = await this.app.vault.read(colophonFile);
            let data = JSON.parse(content);
            let modified = false;

            const updateLinks = (node) => {
                if (node.type === 'internalLink' && node.attrs && node.attrs.target === oldPath) {
                    node.attrs.target = file.path;
                    modified = true;
                }
                if (node.content && Array.isArray(node.content)) {
                    node.content.forEach(updateLinks);
                }
            };

            updateLinks(data.doc);

            if (modified) {
                await this.app.vault.modify(colophonFile, JSON.stringify(data, null, 2));
                await this.indexFile(colophonFile); // Update shadow file
            }
        }
    }
}
